export const ADD_NEW_REVIEW_REQUEST = "ADD_NEW_REVIEW_REQUEST";
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS";
export const ADD_NEW_REVIEW_FAIL = "ADD_NEW_REVIEW_FAIL";
export const ADD_NEW_REVIEW_RESET = "ADD_NEW_REVIEW_RESET";
