export const COMPLETE_COURSE_FOR_MENTOR_REQUEST =
  "COMPLETE_COURSE_FOR_MENTOR_REQUEST";
export const COMPLETE_COURSE_FOR_MENTOR_SUCCESS =
  "COMPLETE_COURSE_FOR_MENTOR_SUCCESS";
export const COMPLETE_COURSE_FOR_MENTOR_FAIL =
  "COMPLETE_COURSE_FOR_MENTOR_FAIL";
export const COMPLETE_COURSE_FOR_MENTOR_RESET =
  "COMPLETE_COURSE_FOR_MENTOR_RESET";
