export const GET_BASIC_INFO_FOR_CHILD_REQUEST =
  "GET_BASIC_INFO_FOR_CHILD_REQUEST";
export const GET_BASIC_INFO_FOR_CHILD_SUCCESS =
  "GET_BASIC_INFO_FOR_CHILD_SUCCESS";
export const GET_BASIC_INFO_FOR_CHILD_FAIL = "GET_BASIC_INFO_FOR_CHILD_FAIL";
