export const GET_COURSE_DATA_FOR_CHECKOUT_REQUEST =
  "GET_COURSE_DATA_FOR_CHECKOUT_REQUEST";
export const GET_COURSE_DATA_FOR_CHECKOUT_SUCCESS =
  "GET_COURSE_DATA_FOR_CHECKOUT_SUCCESS";
export const GET_COURSE_DATA_FOR_CHECKOUT_FAIL =
  "GET_COURSE_DATA_FOR_CHECKOUT_FAIL";
