export const GET_SUBSCRIPTIONS_FOR_CHILD_REQUEST =
  "GET_SUBSCRIPTION_FOR_CHILD_REQUEST";
export const GET_SUBSCRIPTIONS_FOR_CHILD_SUCCESS =
  "GET_SUBSCRIPTION_FOR_CHILD_SUCCESS";
export const GET_SUBSCRIPTIONS_FOR_CHILD_FAIL =
  "GET_SUBSCRIPTION_FOR_CHILD_FAIL";
