export const GET_SUBSCRIPTIONS_FOR_CHILD_HOME_REQUEST =
  "GET_SUBSCRIPTION_FOR_CHILD_HOME_REQUEST";
export const GET_SUBSCRIPTIONS_FOR_CHILD_HOME_SUCCESS =
  "GET_SUBSCRIPTION_FOR_CHILD_HOME_SUCCESS";
export const GET_SUBSCRIPTIONS_FOR_CHILD_HOME_FAIL =
  "GET_SUBSCRIPTION_FOR_CHILD_HOME_FAIL";
