export const GUARDIAN_GET_BASIC_INFO_REQUEST =
  "GUARDIAN_GET_BASIC_INFO_REQUEST";
export const GUARDIAN_GET_BASIC_INFO_SUCCESS =
  "GUARDIAN_GET_BASIC_INFO_SUCCESS";
export const GUARDIAN_GET_BASIC_INFO_FAIL = "GUARDIAN_GET_CHILDREN_FAIL";
