export const GUARDIAN_REGISTER_REQUEST = "GUARDIAN_REGISTER_REQUEST";
export const GUARDIAN_REGISTER_SUCCESS = "GUARDIAN_REGISTER_SUCCESS";
export const GUARDIAN_REGISTER_FAIL = "GUARDIAN_REGISTER_FAIL";
