export const GUARDIAN_LOGIN_REQUEST = "GUARDIAN_LOGIN_REQUEST";
export const GUARDIAN_LOGIN_SUCCESS = "GUARDIAN_LOGIN_SUCCESS";
export const GUARDIAN_LOGIN_FAIL = "GUARDIAN_LOGIN_FAIL";
export const GUARDIAN_LOGIN_RESET_ERROR = "GUARDIAN_LOGIN_RESET_ERROR";
export const GUARDIAN_LOGOUT = "GUARDIAN_LOGOUT";
