export const GUARDIAN_GET_CHILDREN_REQUEST = "GUARDIAN_GET_CHILDREN_REQUEST";
export const GUARDIAN_GET_CHILDREN_SUCCESS = "GUARDIAN_GET_CHILDREN_SUCCESS";
export const GUARDIAN_GET_CHILDREN_FAIL = "GUARDIAN_GET_CHILDREN_FAIL";
