export const GUARDIAN_UPDATE_BASIC_INFO_REQUEST =
  "GUARDIAN_UPDATE_BASIC_INFO_REQUEST";
export const GUARDIAN_UPDATE_BASIC_INFO_SUCCESS =
  "GUARDIAN_UPDATE_BASIC_INFO_SUCCESS";
export const GUARDIAN_UPDATE_BASIC_INFO_FAIL =
  "GUARDIAN_UPDATE_BASIC_INFO_FAIL";
export const GUARDIAN_UPDATE_BASIC_INFO_RESET =
  "GUARDIAN_UPDATE_BASIC_INFO_RESET";
