export const HERO_LOGIN_REQUEST = "HERO_LOGIN_REQUEST";
export const HERO_LOGIN_SUCCESS = "HERO_LOGIN_SUCCESS";
export const HERO_LOGIN_FAIL = "HERO_LOGIN_FAIL";
export const HERO_LOGIN_RESET_ERROR = "HERO_LOGIN_RESET_ERROR";
export const HERO_LOGOUT = "HERO_LOGOUT";
