export const HERO_REGISTER_REQUEST = "HERO_REGISTER_REQUEST";
export const HERO_REGISTER_SUCCESS = "HERO_REGISTER_SUCCESS";
export const HERO_REGISTER_FAIL = "HERO_REGISTER_FAIL";
export const HERO_REGISTER_RESET_ERROR = "HERO_REGISTER_RESET_ERROR";
