export const MENTOR_UPDATE_STATUS_REQUEST = "MENTOR_UPDATE_STATUS_REQUEST";
export const MENTOR_UPDATE_STATUS_SUCCESS = "MENTOR_UPDATE_STATUS_SUCCESS";
export const MENTOR_UPDATE_STATUS_FAIL = "MENTOR_UPDATE_STATUS_FAIL";
