export const MENTOR_GET_CONTROL_COURSE_DETAILS_REQUEST =
  "MENTOR_GET_CONTROL_COURSE_DETAILS_REQUEST";
export const MENTOR_GET_CONTROL_COURSE_DETAILS_SUCCESS =
  "MENTOR_GET_CONTROL_COURSE_DETAILS_SUCCESS";
export const MENTOR_GET_CONTROL_COURSE_DETAILS_FAIL =
  "MENTOR_GET_CONTROL_COURSE_DETAILS_FAIL";
export const MENTOR_GET_CONTROL_COURSE_DETAILS_RESET =
  "MENTOR_GET_CONTROL_COURSE_DETAILS_RESET";
