export const MENTOR_BASICINFO_REQUEST = "MENTOR_BASICINFO_REQUEST";
export const MENTOR_BASICINFO_SUCCESS = "MENTOR_BASICINFO_SUCCESS";
export const MENTOR_BASICINFO_FAIL = "MENTOR_BASICINFO_FAIL";
export const MENTOR_BASICINFO_RESET = "USER_DETAILS_RESET";
