export const MENTOR_CANCEL_APPOINTMENT_REQUEST =
  "MENTOR_CANCEL_APPOINTMENT_REQUEST";
export const MENTOR_CANCEL_APPOINTMENT_SUCCESS =
  "MENTOR_CANCEL_APPOINTMENT_SUCCESS";
export const MENTOR_CANCEL_APPOINTMENT_FAIL = "MENTOR_CANCEL_APPOINTMENT_FAIL";
