export const MENTOR_DELETE_APPOINTMENT_REQUEST =
  "MENTOR_DELETE_APPOINTMENT_REQUEST";
export const MENTOR_DELETE_APPOINTMENT_SUCCESS =
  "MENTOR_DELETE_APPOINTMENT_SUCCESS";
export const MENTOR_DELETE_APPOINTMENT_FAIL = "MENTOR_DELETE_APPOINTMENT_FAIL";
export const MENTOR_DELETE_APPOINTMENT_RESET =
  "MENTOR_DELETE_APPOINTMENT_RESET";
