export const MENTOR_UPDATE_COURSE_REQUEST = "MENTOR_UPDATE_COURSE_REQUEST";
export const MENTOR_UPDATE_COURSE_SUCCESS = "MENTOR_UPDATE_COURSE_SUCCESS";
export const MENTOR_UPDATE_COURSE_FAIL = "MENTOR_UPDATE_COURSE_FAIL";
export const MENTOR_UPDATE_COURSE_RESET = "MENTOR_UPDATE_COURSE_RESET";
