export const MENTOR_PROFILE_DETAILS_REQUEST = "MENTOR_PROFILE_DETAILS_REQUEST";
export const MENTOR_PROFILE_DETAILS_SUCCESS = "MENTOR_PROFILE_DETAILS_SUCCESS";
export const MENTOR_PROFILE_DETAILS_FAIL = "MENTOR_PROFILE_DETAILS_FAIL";
