export const MENTOR_LOGIN_REQUEST = "MENTOR_LOGIN_REQUEST";
export const MENTOR_LOGIN_SUCCESS = "MENTOR_LOGIN_SUCCESS";
export const MENTOR_LOGIN_FAIL = "MENTOR_LOGIN_FAIL";
export const MENTOR_LOGIN_RESET_ERROR = "MENTOR_LOGIN_RESET_ERROR";
export const MENTOR_LOGOUT = "MENTOR_LOGOUT";
