export const MENTOR_ADD_NEW_APPOINTMENT_REQUEST =
  "MENTOR_ADD_NEW_APPOINTMENT_REQUEST";
export const MENTOR_ADD_NEW_APPOINTMENT_SUCCESS =
  "MENTOR_ADD_NEW_APPOINTMENT_SUCCESS";
export const MENTOR_ADD_NEW_APPOINTMENT_FAIL =
  "MENTOR_ADD_NEW_APPOINTMENT_FAIL";
export const MENTOR_ADD_NEW_APPOINTMENT_RESET =
  "MENTOR_ADD_NEW_APPOINTMENT_RESET";
