export const MENTOR_ADD_NEW_COURSE_REQUEST = "MENTOR_ADD_NEW_COURSE_REQUEST";
export const MENTOR_ADD_NEW_COURSE_SUCCESS = "MENTOR_ADD_NEW_COURSE_SUCCESS";
export const MENTOR_ADD_NEW_COURSE_FAIL = "MENTOR_ADD_NEW_COURSE_FAIL";
