export const MENTOR_PROFILE_COURSES_LIST_REQUEST =
  "MENTOR_PROFILE_COURSES_LIST_REQUEST";
export const MENTOR_PROFILE_COURSES_LIST_SUCCESS =
  "MENTOR_PROFILE_COURSES_LIST_SUCCESS";
export const MENTOR_PROFILE_COURSES_LIST_FAIL =
  "MENTOR_PROFILE_COURSES_LIST_FAIL";
