export const MENTOR_REGISTER_REQUEST = "MENTOR_REGISTER_REQUEST";
export const MENTOR_REGISTER_SUCCESS = "MENTOR_REGISTER_SUCCESS";
export const MENTOR_REGISTER_FAIL = "MENTOR_REGISTER_FAIL";
export const MENTOR_REGISTER_RESET_ERROR = "MENTOR_REGISTER_RESET_ERROR";
