export const MENTOR_UPDATE_BASICINFO_REQUEST =
  "MENTOR_UPDATE_BASICINFO_REQUEST";
export const MENTOR_UPDATE_BASICINFO_SUCCESS =
  "MENTOR_UPDATE_BASICINFO_SUCCESS";
export const MENTOR_UPDATE_BASICINFO_FAIL = "MENTOR_UPDATE_BASICINFO_FAIL";
export const MENTOR_UPDATE_BASICINFO_RESET = "MENTOR_UPDATE_BASICINFO_RESET";
