export const MENTOR_COURSES_DASHBOARD_REQUEST =
  "MENTOR_COURSES_DASHBOARD_REQUEST";
export const MENTOR_COURSES_DASHBOARD_SUCCESS =
  "MENTOR_COURSES_DASHBOARD_SUCCESS";
export const MENTOR_COURSES_DASHBOARD_FAIL = "MENTOR_COURSES_DASHBOARD_FAIL";
