export const MENTOR_EDIT_COURSE_DETAILS_REQUEST =
  "MENTOR_EDIT_COURSE_DETAILS_REQUEST";
export const MENTOR_EDIT_COURSE_DETAILS_SUCCESS =
  "MENTOR_EDIT_COURSE_DETAILS_SUCCESS";
export const MENTOR_EDIT_COURSE_DETAILS_FAIL =
  "MENTOR_EDIT_COURSE_DETAILS_FAIL";
export const MENTOR_EDIT_COURSE_DETAILS_RESET =
  "MENTOR_EDIT_COURSE_DETAILS_RESET";
