export const UPDATE_PICTURE_FOR_MENTOR_REQUEST =
  "UPDATE_PICTURE_FOR_MENTOR_REQUEST";
export const UPDATE_PICTURE_FOR_MENTOR_SUCCESS =
  "UPDATE_PICTURE_FOR_MENTOR_SUCCESS";
export const UPDATE_PICTURE_FOR_MENTOR_FAIL = "UPDATE_PICTURE_FOR_MENTOR_FAIL";
export const UPDATE_PICTURE_FOR_MENTOR_RESET =
  "UPDATE_PICTURE_FOR_MENTOR_RESET";
