export const UPDATE_BASIC_INFO_FOR_CHILD_REQUEST =
  "UPDATE_BASIC_INFO_FOR_CHILD_REQUEST";
export const UPDATE_BASIC_INFO_FOR_CHILD_SUCCESS =
  "UPDATE_BASIC_INFO_FOR_CHILD_SUCCESS";
export const UPDATE_BASIC_INFO_FOR_CHILD_FAIL =
  "UPDATE_BASIC_INFO_FOR_CHILD_FAIL";
export const UPDATE_BASIC_INFO_FOR_CHILD_RESET =
  "UPDATE_BASIC_INFO_FOR_CHILD_RESET";
